### ISSUE TITLE
Errors trying to use installed extension

### ISSUE THREAD

**Issue by notABluesSinger** [nicolabosco87/ttl-enhance#8]
I downloaded the chrome release and have it insalled as an unpacked extnesion, but it's not working. Inspecting the error output I see
``` 
"__chrome|opera|edge|dev__content_security_policy": {
    "extension_pages": "script-src 'self' http://localhost:8097; object-src 'self'"
  },
```

**Comment by notABluesSinger** [comment]
This appears to be working - I think I just didn't realise that it would add a button to the app and was trying to interact with the extensions icon in the browser.

**Comment by nicolabosco87** [comment]
Right, I should write more infos in the readme. I'll do that in the next release.
